// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9s9iIUJGi9kPVI9j3VQ0asFgRAIIM5bU',
    appId: '1:780487203873:web:ff0d58f27706334bbc5760',
    messagingSenderId: '780487203873',
    projectId: 'fir-apps-a7dd4',
    authDomain: 'fir-apps-a7dd4.firebaseapp.com',
    databaseURL:
        'https://fir-apps-a7dd4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-apps-a7dd4.appspot.com',
    measurementId: 'G-2CT91GPBEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8j4LfkWJS3LJU64ETAXFTsO_VX2bhHLY',
    appId: '1:780487203873:android:00c6b20682ff17f8bc5760',
    messagingSenderId: '780487203873',
    projectId: 'fir-apps-a7dd4',
    databaseURL:
        'https://fir-apps-a7dd4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-apps-a7dd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiD4meJ6HILXCzkzb8oXG-wyb2p0czsWM',
    appId: '1:780487203873:ios:61d03c5ded0f2502bc5760',
    messagingSenderId: '780487203873',
    projectId: 'fir-apps-a7dd4',
    databaseURL:
        'https://fir-apps-a7dd4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-apps-a7dd4.appspot.com',
    androidClientId:
        '780487203873-bs89fv7it9mh3p21bqfhr87jhfp14deg.apps.googleusercontent.com',
    iosClientId:
        '780487203873-fekohop6oraenvso3un2sjotudvog1vj.apps.googleusercontent.com',
    iosBundleId: 'com.tbib.demo.msStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiD4meJ6HILXCzkzb8oXG-wyb2p0czsWM',
    appId: '1:780487203873:ios:61d03c5ded0f2502bc5760',
    messagingSenderId: '780487203873',
    projectId: 'fir-apps-a7dd4',
    databaseURL:
        'https://fir-apps-a7dd4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-apps-a7dd4.appspot.com',
    androidClientId:
        '780487203873-bs89fv7it9mh3p21bqfhr87jhfp14deg.apps.googleusercontent.com',
    iosClientId:
        '780487203873-fekohop6oraenvso3un2sjotudvog1vj.apps.googleusercontent.com',
    iosBundleId: 'com.tbib.demo.msStore',
  );
}
